const GATEWAY = "gateway";
const PHONE = "phone";
const CAR = "car";

const BUFLEN = 1000000;	//Max length of buffer

const TIME_BASE         = 10;   // 10 ms
const SYNC_PERIOD_TICKS = 10;   // 10 * TIME_BASE = 100 ms
const ALIVE_TIMEOUT     = 2000; // 2 seconds

const DATA_BYTE_LEN_MAX = 32;
const SYNC_MESSAGE_LEN_MIN = 7; // ID(4), DLC (1), Status(1), Data(1)

const CAN_DIRECTION_TX = 0;
const CAN_DIRECTION_RX = 1;

const CAN_MSG_STATUS_UPDATED        = 0x01;
const CAN_MSG_STATUS_CHANGED        = 0x02;
const CAN_MSG_STATUS_OVERWRITE      = 0x04;
const CAN_MSG_STATUS_NEVER_SENT     = 0x08;
const CAN_MSG_STATUS_NEVER_RECEIVED = 0x40;
const CAN_MSG_STATUS_E2E_PROFILE_05 = 0x10;
const CAN_MSG_STATUS_E2E_PROFILE_11 = 0x20;
const CAN_MSG_STATUS_CLEAR_FLAGS = ( CAN_MSG_STATUS_UPDATED | CAN_MSG_STATUS_CHANGED | CAN_MSG_STATUS_OVERWRITE 
									| CAN_MSG_STATUS_NEVER_SENT | CAN_MSG_STATUS_NEVER_RECEIVED );

module.exports = {
	GATEWAY,
	PHONE,
	CAR,
	
	BUFLEN,
	
	TIME_BASE,
	SYNC_PERIOD_TICKS,
	ALIVE_TIMEOUT,
	
	DATA_BYTE_LEN_MAX,
	SYNC_MESSAGE_LEN_MIN,

	CAN_DIRECTION_TX,
	CAN_DIRECTION_RX,

	CAN_MSG_STATUS_UPDATED,
	CAN_MSG_STATUS_CHANGED,
	CAN_MSG_STATUS_OVERWRITE,
	CAN_MSG_STATUS_NEVER_SENT,
	CAN_MSG_STATUS_NEVER_RECEIVED,
	CAN_MSG_STATUS_E2E_PROFILE_05,
	CAN_MSG_STATUS_E2E_PROFILE_11,
	CAN_MSG_STATUS_CLEAR_FLAGS
}